defaults:
  - _self_
  - model: roberta-large
  - method: laplace

model:
  batch_size: 32 # 8 for llama
  eval_batch_size: 8 # 2 for llama

experiment:
  seed: 10
  use_loraxs: True # whether to use LoRa-XS or LoRa modules
  skip_training: False # whether to skip training and only do evaluation

  val_split_size: 0.2
  gradient_accumulation_steps: 1

  task: "mrpc"
  subtask: ""
  ood_task: "" # leave empty for no OOD evaluation
  ood_subtask: ""
  ood_batch_size: 16
  learning_rate: 1e-3
  cls_learning_rate: 1e-3 # classifier learning rate
  # weight decays
  lora_weight_decay: 0.01
  classifier_weight_decay: 0.01

  num_epochs: 15
  set_fraction: 1.0 # fraction of training dataset used for learning (value between 0 and 1, inclusively)
  save_checkpoints_at_epochs: [4, 5, 6] # epochs at which to save checkpoints during training
  scheduler: "linear"
  warmup_length: 0.06
  num_lr_cycles: 0.5

  # wandb parameters
  wandb_entity: "loquacious"
  wandb_project: "bayes-llm"
  wandb_group: "default"
  wandb_mode: "online" # "online"

  # lora hyperparams
  lora_r: 8
  lora_alpha: 16
  lora_dropout: 0.0
  train_biases: "none"
  # Unfreeze Parameters
  unfreeze_A: False
  unfreeze_B: False
  extend_target_modules: False
  # LoRa-XS parameters
  loraxs_sigma: 0.00001
  loraxs_mode: "normal"
  add_lm_head: False # whether to target ["lm_head"] module as was done in Laplace paper

  exp_group_name: "linearization" # "new_exp"
  save_folder: "/net/storage/pr3/plgrid/plggploraxs/plgloquacious/laplace_results" # default save location
  save_path: "./should_not_be_saving_here" # will get replaced
  exp_name: "" # will get replaced unless it is set by the user

  overwrite: False
  data_path: "./need_folder_specification" # /path/to/your/data
  model_path: "./need_folder_specification" # /path/to/your/models (for offline loading)
  wandb_path: "/net/storage/pr3/plgrid/plggploraxs/plgloquacious/.cache/wandb" # /path/to/wandb

  mnli_model_path: "./model_checkpoints/MNLI" # path to pretrained LoRa-XS weights for given rank on MNLI task
  # used only for RTE and MRPC tasks
  offline: False

evaluation:
  seed: 10

hydra:
  run:
    dir: "test" # hydra output dir
