reconstruction_type: "dct-1/2_svd"
reconstr_mode: "separated"
half_init_dec: False
replacement_module_random_init: False
r_squared: True
dct-1/2_svd:
  n_iter: 10
  random_state: 42
  dct_select_by: "top-left"
